### ISSUE TITLE
Notification UI

### ISSUE THREAD

**Issue by r4stered** [cse442-fall-2019-offering/442projects-the_null_terminators#1]
As a student, I want to be able to get a notification when a class is soon, so I can leave for class on time.

**Comment by r4stered** [comment]
1. Create an event
2. Wait for event to happen
3. Desktop notification should be sent with event name and time

**Comment by ajwoloszyn** [comment]
### Test Script
1. Start application normally
   - Application should open, then a small dialog box should appear over it
   - Dialog should have a title with the name of the event, the date and time of the event, and a description of the event
2. Close the dialog box
   - Dialog box should close
