### ISSUE TITLE
Create notification pop-up

### ISSUE THREAD

**Issue by max-wojtczak** [cse442-fall-2019-offering/442projects-the_null_terminators#12]

**Comment by ajwoloszyn** [comment]
###Test Script
1. Start application normally
-Application should open, then a small dialog box should appear over it
-Dialog should have a title with the name of the event, the date and time of the event, and a description of the event
2. Close the dialog box
-Dialog box should close

**Comment by ajwoloszyn** [comment]
### Test Script
1. Start application normally
   - Application should open, then a small dialog box should appear over it
   - Dialog should have a title with the name of the event, the date and time of the event, and a description of the event
2. Close the dialog box
   - Dialog box should close
