### ISSUE TITLE
Create buttons to switch between month views

### ISSUE THREAD

**Issue by max-wojtczak** [cse442-fall-2019-offering/442projects-the_null_terminators#15]

**Comment by marksng** [comment]
1. Start the application. 
    The calendar application should open, with a small test dialog. Close it. 
2. Attempt to switch months. 
    If > pressed ->
        The next month should be shown (eg, September to October) 
    If < pressed -> 
        The previous month should be show (eg, September to August) 
    If TODAY pressed ->
        Current month should be shown.
